### ISSUE TITLE
Remove ESLint monkey patching

### ISSUE THREAD

**Issue by pveyes** [traveloka/javascript#1]
Currently we monkey patch eslint before running tests because `no-unused-vars` rule with `babel-eslint` parser causing weird error

```
    TypeError: Cannot read property 'type' of undefined
      
      at isForInRef (../../node_modules/eslint/lib/rules/no-unused-vars.js:360:23)
      at ../../node_modules/eslint/lib/rules/no-unused-vars.js:401:21
      at Array.some (native)
      at isUsedVariable (../../node_modules/eslint/lib/rules/no-unused-vars.js:400:40)
      at collectUnusedVariables (../../node_modules/eslint/lib/rules/no-unused-vars.js:523:26)
      at collectUnusedVariables (../../node_modules/eslint/lib/rules/no-unused-vars.js:530:17)
      at EventEmitter.Program:exit (../../node_modules/eslint/lib/rules/no-unused-vars.js:590:36)
      at emitOne (events.js:82:20)
      at EventEmitter.emit (events.js:169:7)
      at NodeEventGenerator.leaveNode (../../node_modules/eslint/lib/util/node-event-generator.js:49:22)
      at CodePathAnalyzer.leaveNode (../../node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:628:23)
      at CommentEventGenerator.leaveNode (../../node_modules/eslint/lib/util/comment-event-generator.js:110:23)
      at Controller.leave (../../node_modules/eslint/lib/eslint.js:921:36)
      at Controller.__execute (../../node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
      at Controller.traverse (../../node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
      at Controller.Traverser.controller.traverse (../../node_modules/eslint/lib/util/traverser.js:36:33)
      at EventEmitter.module.exports.api.verify (../../node_modules/eslint/lib/eslint.js:915:23)
      at processText (../../node_modules/eslint/lib/cli-engine.js:262:31)
      at CLIEngine.executeOnText (../../node_modules/eslint/lib/cli-engine.js:749:26)
      at runEslint (src/__tests__/rule-test.js:13:17)
      at Object.<anonymous> (src/__tests__/rule-test.js:21:20)
      at process._tickCallback (node.js:369:9)
```

**Comment by pveyes** [comment]
Update: cloning new `babel-eslint` repo and using parser option set to index.js inside cloned babel-eslint repo using require.resolve works
